#Server Configuration
server:
  port: 8081
#Spring Configuration
spring:
  application:
    name: softdevteam_test
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${RDS_HMSOFT_DEV_URL}
    hikari:
      username: ${RDS_HMSOFT_DEV_USER}
      password: ${RDS_HMSFOT_DEV_PASSWORD}
      connection-timeout: 10000
      idle-timeout: 50000
      minimum-idle: 0
      maximum-pool-size: 10
      connection-test-query: select 1
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    open-in-view: false
    generate-ddl: true
